### ISSUE TITLE
Cannot withdraw from Tornado.cash

### ISSUE THREAD

**Issue by isthrowaway** [tornadocash/tornado-core#34]
Trying to withdraw 1 eth using my note + metamask which fails and receiving the following error message 'TypeError: Cannot convert null to a BigInt'. 

Submitting the note shows all the right details about the deposit, I then click withdraw, the 'generating proofs' loading screen shows, and the error shows up in the console, and in your UI under the recipient address field. 

Can you please fix this so I can withdraw my funds?

**Comment by pertsev** [comment]
What is your browser version?

**Comment by isthrowaway** [comment]
Brave Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit) although also happened to me on Chrome

Other errors (are consoled out whilst 'generating proof'):
-Uncaught (in promise) TypeError: Cannot read property 'realUrl' of undefined
-Uncaught (in promise) ChunkLoadError: Loading chunk 5 failed.

**Comment by isthrowaway** [comment]
Was finally able to withdraw after many failed attempts with my browser extensions enabled. I had the following extensions enabled - Privacy badger, uBlock Origin. Disabling them allowed me to complete the withdrawal in Brave. I have those extensions enabled in Chrome too. So maybe they were the issue? Great service!
