### ISSUE TITLE
Data for relayer (according to WP)

### ISSUE THREAD

**Issue by fastchain** [tornadocash/tornado-core#36]
Hello, 
Thank you for a great tool! I'm trying to figure out with the white paper and its bit unclear at the withdrawal section:

>• Send a request to Relayer supplying transaction data R, h, A, f, t, P. The Relayer is then
supposed to make a transaction to contract C with supplied data.

It's not clear, why t (relayer's address) should be provided, isn't relayer knows own address?

Thank you!

**Comment by poma** [comment]
relayer's address is included in proof data in order to prevent frontrunning. The smart contract will pay the fee only to relayer address that is embedded in the proof even if someone else frontruns and submits this proof first.

**Comment by fastchain** [comment]
@poma thank you very much for the comment, but the question is slightly different (plz excuse me if I wasn't clear enough), the question is why should sender  provide a t-address to a relayer.

**Comment by poma** [comment]
Sender provides all SNARK pubic inputs as is, even if relayer might already know some of them

**Comment by fastchain** [comment]
@poma  now it's clear, thank you for your detailed explanation!
