### ISSUE TITLE
Please support MetaMask!

### ISSUE THREAD

**Issue by ytrezq** [tornadocash/tornado-core#42]
MetaMask is the most used web software wallet.
Please support it on https://tornado.cash.

**Comment by pertsev** [comment]
We do support the Metamask. Click the "connect" button at the top right of the page.

**Comment by ytrezq** [comment]
@pertsev it lists `Portis` `Squarelink` and `Fortmatic` but Metamask isn t among the options.

**Comment by pertsev** [comment]
@ytrezq then you need to install the metamask first. After then it will be listed on UI

![image](https://user-images.githubusercontent.com/11399003/76311120-4d2a4180-62e1-11ea-82d3-5d6e8d75aaa7.png)

**Comment by ytrezq** [comment]
@pertsev : sorry thank you.

how I can configure this repository to be compatible with the official contracts already deployed on mainnet?

**Comment by pertsev** [comment]
@ytrezq it is already configured. You can use cli.js to interact with mainnet and kovan contracts

https://github.com/tornadocash/tornado-core#kovan-mainnet

**Comment by ytrezq** [comment]
@pertsev : no I mean for using `cli.js`. It’ written that I need to set `PRIVATE_KEY` inside `.env`. But I suppose that if I do use my own private key (I don’t even know the private key of what), that the transactions I’ll build won’t be compatible with the official contract.

Currently, nothing happens when I do `./cli.js --help` on the lastest Fedora.

**Comment by pertsev** [comment]
You need to 
1. install dependencies - `npm i`
2. provide the PRIVATE_KEY of the account you are going to deposit from. This account will be used to withdrawal if you don't use a relayer (`--relayer <URL>` option)

**Comment by ytrezq** [comment]
@pertsev : ok. In that case, is there a prebuilt version that would allow me to `run.js` ?

Because in that case, `npm` fails to build circomlib ; keccak ; sha3 and many others dependencies (I’m on Fedora). I mean the usual nightmare.

**Comment by ytrezq** [comment]
@pertsev : so I can’t use it.

**Comment by pertsev** [comment]
@ytrezq sorry. There is no prebuild version. What the node and npm versions you use? It works fine for
```
node v11.15.0
npm 6.13.1
```

**Comment by ytrezq** [comment]
> ytrezq sorry. There is no prebuild version. What the node and npm versions you use? It works fine for
> node v11.15.0
> npm 6.13.1

@pertsev : In the case of sha3 and keccak@1.4.0 the logs doesn’t even seems to contain an error.

I’m using those versions through official Fedora 30 packages and it doesn’t works. I also have `gcc` `git` `svn` being installed. I’m out of testing. Is there a way to get the `node_modules` directory from `https://tornado.cash` ?
