### ISSUE TITLE
tornado cash DApp error reporting blocking deposit and withdraw

### ISSUE THREAD

**Issue by Aaaaaashu** [tornadocash/tornado-core#44]
- iOS 13.4
- imToken DApp Browser

> When I load the DApp, I get an error message (Multiple tabs opened), and withdraw I get an error message (Bignumber issue)

![641585542128_ pic_hd](https://user-images.githubusercontent.com/3678166/77987530-a1f33200-734c-11ea-82d5-71d2d072eaec.jpg)

![Image from iOS](https://user-images.githubusercontent.com/3678166/77987540-a9b2d680-734c-11ea-9349-2f2994f5c0d2.png)

**Comment by pertsev** [comment]
Hello @Aaaaaashu The first one is the expected behavior. The second issue is fixed now.
