### ISSUE TITLE
"Multiple tabs opened" error on iOS

### ISSUE THREAD

**Issue by zhangzhongnan928** [tornadocash/tornado-core#47]
hi mate, I tried tornado.cash on AlphaWallet, imToken, TrustWallet and Safari with different iOS devices.  all show the same error message.‬
![IMG_2459](https://user-images.githubusercontent.com/33795543/78847167-6134a080-7a51-11ea-8522-9cf9fe535986.PNG) 
![IMG_2458](https://user-images.githubusercontent.com/33795543/78847169-6265cd80-7a51-11ea-826e-95c68e1aaabc.PNG)
![IMG_2457](https://user-images.githubusercontent.com/33795543/78847171-62fe6400-7a51-11ea-94ea-aaaabf3b658c.PNG)
![IMG_2460](https://user-images.githubusercontent.com/33795543/78847163-5bd75600-7a51-11ea-80e1-7993afd651ad.PNG)

**Comment by pertsev** [comment]
@zhangzhongnan928 Thanks for the report. Fixed now, please try again.
