### ISSUE TITLE
Offer the cheapest relayer by default

### ISSUE THREAD

**Issue by leafcutterant** [tornadocash/tornado-core#49]
The default choice of relay usually calculates the transaction fee with 4x the gas price that would make sense for next-block inclusion, and charges 0.5-2% by volume. Meanwhile, other relays in the list are much cheaper and sensible. Also, the relay choice setting is quite well-hidden and most people never realize they have options, so they will just go along with the default offer, which is the most expensive of all.

This makes no sense from a price competitiveness standpoint, and questions your integrity. One can imagine a scenario where you have an cartel agreement with this relayer: you make them default, they rip off people and share the inflated income with you. Maybe it's time to prove this is not the case by always offering the cheapest reachable relayer and making the relayer choice setting more visible.

**Comment by rstormsf** [comment]
It's open sourced protocol, feel free to build the UI the way you feel it's right for you. 
There is NO default relayer. The array of relayers is loaded and a random one is picked. 
The user ALWAYS has a choice to select whoever they like.

**Comment by leafcutterant** [comment]
> There is NO default relayer. The array of relayers is loaded and a random one is picked.

Great, then maybe it was just bad luck on my side. Would you agree it would help Tornado to gain traction if the UI offered the cheapest available relayer?

**Comment by rstormsf** [comment]
@leafcutterant I don't think so.

**Comment by leafcutterant** [comment]
How so?
