### ISSUE TITLE
Remove as many external website connections as possible

### ISSUE THREAD

**Issue by leafcutterant** [tornadocash/tornado-core#51]
Tornado.cash makes connections to these domains:

```
tornado.cash
ethgasstation.info
fairish.net
fonts.googleapis.com
infura.io
kovan.website
mainnet-frelay.duckdns.org
nyuels.de
poa.network
us.to
youtube.com
zoltu.io
```

This is quite a lot for a service that is meant to preserve privacy, especially with the inclusion of Googleapis and Youtube. It damages the anonymity sets. It would be good to remove as many of these as possible and connect to the rest with your server, as far as it increases user privacy.

**Comment by poma** [comment]
Most of those are relayers which are checked for online status (at page load so that the list is ready when user gets to withdrawal step):
```
fairish.net
kovan.website
mainnet-frelay.duckdns.org
nyuels.de
poa.network
us.to
zoltu.io
```

fonts.googleapis.com and youtube can be removed I think. 

ethgasstation and infura are obviously needed to get chain state and gas prices

**Comment by leafcutterant** [comment]
> fonts.googleapis.com and youtube can be removed I think.

Thank you Roman, that would be a great step forward!

With regards to the rest, would it be possible that the Tornado server obtains the information from the relayers and passes it on to the user, without the user having to connect to those domains? I don't know how practical this would be but my intuition is that, from a privacy standpoint, the user is worse off by connecting to more domains.

**Comment by poma** [comment]
This will check the connectivity from tornado server to relayers instead from user to relayers, which can be different (ip bans, firewalls etc.). Also there is no such thing as Tornado server as it will be a point of centralisation. There is only frontend that can be served from anywhere.

**Comment by rstormsf** [comment]
Tornado doesn't have a server

**Comment by rstormsf** [comment]
Youtube and google fonts are removed in `Tornado.cash v2.33`
