### ISSUE TITLE
Display recent withdrawals

### ISSUE THREAD

**Issue by leafcutterant** [tornadocash/tornado-core#52]
Similarly to how deposits are displayed for each note type, also display withdrawals to support the user in choosing an optimal withdrawal time.

**Comment by rstormsf** [comment]
There is etherscan.io for it

**Comment by leafcutterant** [comment]
Could you specify? How can one check withdrawals for a certain note type on Duneanalytics or Etherscan? I haven't found a reliable way to do it.

**Comment by rstormsf** [comment]
![image](https://user-images.githubusercontent.com/9360827/80515589-08ad4080-8937-11ea-8116-674e6c5529ba.png)

![image](https://user-images.githubusercontent.com/9360827/80515600-0ea32180-8937-11ea-87fe-7be7e5bcb814.png)

**Comment by leafcutterant** [comment]
Sorry, maybe I'm missing something but I don't see a list of withdrawals on a per-note basis on either site.

**Comment by poma** [comment]
All 0-cost transactions on etherscan are withdrawals

**Comment by leafcutterant** [comment]
Thanks @poma! That makes it a bit easier.

I'd still say it would help users make better withdrawal timing choices (avoid the deposit and the  withdrawal being next to each other) if you had this information on the site as with deposits. Thank you for your work and for considering this!
