### ISSUE TITLE
tornado.cash cannot read the balance of eth in AlphaWallet

### ISSUE THREAD

**Issue by zhangzhongnan928** [tornadocash/tornado-core#57]
tornado.cash cannot read the balance of eth in AlphaWallet
it is able to read the other balances like DAI etc but not eth.

This is what I get in the console
[Log] sendAsync, method, from, params – "eth_getBalance" – undefined – ["0x42ea529282DDE0AA87B42d9E83316eb23FE62c3f", "latest"] (2) (51304e939a3655ed1e6c.js, line 1)

**Comment by rstormsf** [comment]
it's the issue with AlphaWallet, it works fine in Status.im and Trustwallet.
@zhangzhongnan928

**Comment by zhangzhongnan928** [comment]
> it's the issue with AlphaWallet, it works fine in Status.im and Trustwallet.
> @zhangzhongnan928
> your developer says he doesn't want to fix it:
> [AlphaWallet/alpha-wallet-android#766](https://github.com/AlphaWallet/alpha-wallet-android/issues/766)

Thanks for the feedback, is it the same issue#766 causing the problem here with tornado.cash ?
I find the same "cannot read the balance of eth" issue with tokensets.com as well.

**Comment by rstormsf** [comment]
Yeap, as you can see, it's AlphaWallet issue, not tornadocash. ;-)

**Comment by zhangzhongnan928** [comment]
We will see whether it is fixed with updating the web3 to a higher version.
BTW, I tested tornado.cash on coinbase wallet and cipher; both have the same issue (there may be other wallets which break too).

**Comment by rstormsf** [comment]
Yeap, but it works in Imtoken, Trustwallet, status.im

**Comment by rstormsf** [comment]
@zhangzhongnan928 what is cipher?

**Comment by zhangzhongnan928** [comment]
If I'm not wrong, cipher is one of the first wallets have a dapp browser, I think they are also sold to coinbase ( Toshi is the current coinbase wallet)

https://techcrunch.com/2018/04/13/coinbase-acquires-decentralized-app-browser-wallet-cipher-browser/

*Victor Zhang*
CEO , AlphaWallet

( http://apple.co/2OQRS7c ) ( http://play.google.com/store/apps/details?id=io.stormbird.wallet&hl=en_SG ) ( http://github.com/alphawallet ) ( http://twitter.com/Victor928 ) ( http://www.linkedin.com/in/zhangzhongnan/ ) ( http://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w ) ( http://www.facebook.com/AlphaWallet ) ( http://medium.com/alphawallet )

( https://twitter.com/Victor928 ) RT @Victor928: ( https://twitter.com/Victor928: ) @UniswapProtocol ( https://twitter.com/UniswapProtocol ) V2 is live🎉👍. The UI matches @AlphaWallet ( https://twitter.com/AlphaWallet ) very well😆🤩🥰 https://t.co/L4QZE2Grcs Read More ( https://twitter.com/Victor928/statuses/1262513171778207745 )

Create your own WiseStamp email signature ( https://www.wisestamp.com/signature-in-email/?utm_source=promotion&utm_medium=signature&utm_campaign=create_your_own&srcid=5006976067829760 )

**Comment by rstormsf** [comment]
@zhangzhongnan928 which is coinbase wallet which works fine with tornado.cash( just tried)

**Comment by zhangzhongnan928** [comment]
Thanks, @rstormsf for time
