### ISSUE TITLE
Library functions must be implemented if declared.

### ISSUE THREAD

**Issue by lailaibtc** [tornadocash/tornado-core#86]
https://github.com/tornadocash/tornado-core/blob/77af0c5bddfcf9d973efbc38278a249bb0173da3/contracts/MerkleTreeWithHistory.sol#L15

**Comment by Federico2014** [comment]
I get the same problem, Why not publish the `MiMCSponge` solidity source code?

**Comment by rstormsf** [comment]
Please ask original MiMCSponge devs to provide Solidity version

**Comment by poma** [comment]
Because there is no solidity source code, and probably never will be, because it's inefficient

**Comment by Federico2014** [comment]
Here is solidity version: https://gist.github.com/poma/5adb51d49057d0a0edad2cbd12945ac4
it is quite inefficient, but how can you deploy your contracts?  
Furthermore, Why not use the `sha256` or `keccak256`?

**Comment by poma** [comment]
sha and keccak hashes are not snark friendly.

Solidity version from the gist will probably not even fit into max contract size and spends like 5x more gas. Circomlib version is written in EVM assembly and is small and fast.
